/*
 * Copyright (C) 2024 OpenAni and contributors.
 *
 * 此源代码的使用受 GNU AFFERO GENERAL PUBLIC LICENSE version 3 许可证的约束, 可以在以下链接找到该许可证.
 * Use of this source code is governed by the GNU AGPLv3 license, which can be found at the following link.
 *
 * https://github.com/open-ani/ani/blob/main/LICENSE
 */

package me.him188.ani.app.data.models.subject

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import kotlinx.serialization.Serializable

/**
 * 一个标签. 标签可能是由维基人指定的 [公共标签][isCanonical], 也可能是用户自定义的标签.
 *
 * 可通过 [Tag.kind] 获取到对应的公共标签种类 [CanonicalTagKind].
 */
@Serializable
@Immutable
data class Tag(
    val name: String,
    val count: Int,
)

/**
 * 是否为 [Bangumi 公共标签](https://bgm.tv/wiki/tag/list).
 */
@Stable
val Tag.isCanonical: Boolean
    get() = CanonicalTagKind.matchOrNull(name) != null

/**
 * 获取标签的种类, 如果不是公共标签则返回 `null`.
 */
@Stable
val Tag.kind: CanonicalTagKind?
    get() = CanonicalTagKind.matchOrNull(name)

/**
 * Bangumi 定义的公共标签种类.
 */
// https://bgm.tv/wiki/tag/list
// Generated by GPT-4o
// Use list because we want to keep the order
@Immutable
sealed class CanonicalTagKind(val values: List<String>) {
    /**
     * 分类
     */
    @Immutable
    data object Category : CanonicalTagKind(
        listOf("短片", "劇場版", "TV", "OVA", "MV", "CM", "WEB", "PV", "動態漫畫"),
    )

    /**
     * 来源
     */
    @Immutable
    data object Source : CanonicalTagKind(
        listOf("原創", "漫畫改", "遊戲改", "小說改"),
    )

    /**
     * 类型
     */
    @Immutable
    data object Genre : CanonicalTagKind(
        listOf(
            "科幻", "喜劇", "百合", "校園", "驚悚", "後宮", "機戰", "懸疑", "戀愛", "奇幻",
            "推理", "運動", "耽美", "音樂", "戰鬥", "冒險", "萌系", "穿越", "玄幻", "乙女",
            "恐怖", "歷史", "日常", "劇情", "武俠", "美食", "職場",
        ),
    )

    /**
     * 地区
     */
    @Immutable
    data object Region : CanonicalTagKind(
        listOf(
            "歐美", "日本", "美國", "中國", "法國", "韓國", "俄羅斯", "英國",
            "蘇聯", "香港", "捷克", "臺灣",
        ),
    )

    /**
     * 分级
     */
    @Immutable
    data object Rating : CanonicalTagKind(
        listOf("R18"),
    )

    /**
     * 受众
     */
    @Immutable
    data object Audience : CanonicalTagKind(
        listOf("BL", "GL", "子供向", "女性向", "少女向", "少年向", "青年向"),
    )

    /**
     * 设定
     */
    @Immutable
    data object Setting : CanonicalTagKind(
        listOf(
            "魔法少女", "超能力", "偶像", "網遊", "末世", "樂隊",
            "賽博朋克", "宮廷", "都市", "異世界", "性轉", "龍傲天", "鳳傲天",
        ),
    )

    /**
     * 角色
     */
    @Immutable
    data object Character : CanonicalTagKind(
        listOf(
            "制服", "獸耳", "僞娘", "吸血鬼", "妹控", "蘿莉", "傲嬌", "女僕", "巨乳", "電波",
            "動物", "正太", "兄控", "殭屍", "羣像", "美少女", "美少年",
        ),
    )

    /**
     * 情绪
     */
    @Immutable
    data object Emotion : CanonicalTagKind(
        listOf("熱血", "治癒", "溫情", "催淚", "純愛", "友情", "致鬱"),
    )

    /**
     * 技术
     */
    @Immutable
    data object Technology : CanonicalTagKind(
        listOf("黑白", "3D", "水墨", "定格", "粘土", "剪紙", "轉描", "三渲二"),
    )

    /**
     * 系列
     */
    @Immutable
    data object Series : CanonicalTagKind(
        listOf(
            "高達", "東方", "Fate", "空之境界", "柯南", "光之美少女", "哆啦A夢",
            "物語系列", "刀劍神域", "進擊的巨人",
        ),
    )

    @Stable
    companion object {
        @Stable
        val entries by lazy {
            listOf(
                Category, Source, Genre, Region, Rating, Audience,
                Setting, Character, Emotion, Technology, Series,
            )
        }

        // A map to directly associate tags with their corresponding CanonicalTagKind for fast querying
        private val tagMap: Map<String, CanonicalTagKind> by lazy {
            val entries = entries
            buildMap {
                for (kind in entries) {
                    for (value in kind.values) {
                        put(value, kind)
                    }
                }
            }
        }

        /**
         * 获取匹配的 [CanonicalTagKind], 如果没有匹配则返回 `null`.
         */
        fun matchOrNull(tag: String): CanonicalTagKind? = tagMap[tag]
    }
}
